#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:
  peer0:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.${ORG:-org1}.${DOMAIN:-example.com}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb.peer0

  couchdb.peer0:
    container_name: couchdb.peer0.${ORG:-org1}.${DOMAIN:-example.com}
    image: hyperledger/fabric-couchdb
    environment:
    - COUCHDB_USER=
    - COUCHDB_PASSWORD=
    ports:
    - ${PEER0_COUCHDB_PORT:-5084}:5984
    volumes:
      - ./data/couchdb0:/opt/couchdb/data
    restart: always
