#
# Copyright . All Rights Reserved.
#

version: '3.7'


services:
  ca:
    ports:
    - ${CA_PORT:-7054}:7054

  peer0:
    ports:
    - ${PEER0_PORT:-7051}:7051
    - ${PEER0_EVENT_PORT:-7053}:7053

  api:
    ports:
    - ${WWW_PORT:-8080}:80
